services:
    etcd-1:
        image: "quay.io/coreos/etcd:v3.5.10"
        entrypoint: /usr/local/bin/etcd
        environment:
          - ETCD_LOG_LEVEL=debug
        command:
            - '--name=etcd-1'
            - '--logger=zap'
            - '--data-dir=/etcd_data'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--initial-advertise-peer-urls=http://etcd-1:2380'
            - '--advertise-client-urls=http://127.0.0.1:2379'
            - '--initial-cluster-token=etcd-cluster'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
        ports:
            - 2379:2379
            - 12379:2379
        volumes:
            - ./data/etcd-1:/etcd_data
    etcd-2:
        image: "quay.io/coreos/etcd:v3.5.10"
        entrypoint: /usr/local/bin/etcd
        environment:
          - ETCD_LOG_LEVEL=debug
        command:
            - '--name=etcd-2'
            - '--logger=zap'
            - '--data-dir=/etcd_data'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--initial-advertise-peer-urls=http://etcd-2:2380'
            - '--advertise-client-urls=http://127.0.0.1:2479'
            - '--initial-cluster-token=etcd-cluster'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
        ports:
            - 2479:2379
            - 22379:2379
        volumes:
            - ./data/etcd-2:/etcd_data
    etcd-3:
        image: "quay.io/coreos/etcd:v3.5.10"
        entrypoint: /usr/local/bin/etcd
        environment:
          - ETCD_LOG_LEVEL=debug
        command:
            - '--name=etcd-3'
            - '--logger=zap'
            - '--data-dir=/etcd_data'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--initial-advertise-peer-urls=http://etcd-3:2380'
            - '--advertise-client-urls=http://127.0.0.1:2579'
            - '--initial-cluster-token=etcd-cluster'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
        ports:
            - 2579:2379
            - 32379:2379
        volumes:
            - ./data/etcd-3:/etcd_data
